sudo: false

language: ruby
rvm:
  - ruby-head
  - 2.2.6
  - 2.3.3
  - 2.4.0

matrix:
    allow_failures:
        - rvm: ruby-head
        - rvm: 2.2.6
fast_finish: true

branches:
  only:
    - master

before_install: 'gem install bundler -v 1.14.0'

jobs:
  include:
    - stage: specs
      script: 'bundle exec rake spec'
    - stage: rubocop
      script: 'bundle exec rake rubocop'
